---
docker_network_name: database
postgres_version: 0.8.1-pg18-trixie

postgres_users:
  - name: kestra
    password: "{{ kestra_db_password }}"
  - name: readeck
    password: "{{ readeck_db_password }}"
  - name: librechat
    password: "{{ librechat_db_password }}"

postgres_databases:
  - name: kestra
    owner: kestra
    comment: Metadata database for Kestra
    encoding: UTF-8
  - name: readeck
    owner: readeck
    comment: Database for readeck
    encoding: UTF-8
  - name: librechat
    owner: librechat
    comment: Database for librechat
    encoding: UTF-8
    extensions:
      - vector

mongodb_version: 8.2.4

mongodb_users:
  - name: librechat
    password: "{{ librechat_mongodb_password }}"
    roles:
      - db: librechat
        role: readWrite
