default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1a27nce4x2lgvv655sgrmjeq4pnunarnqpy48rrwt2y9c2hc7458skhmqw9"]

[secrets]
CLOUDFLARE_ZONE= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ21WaGNmZ0JWTWRweXZSQmlWM0lSYWlYL3plWmJjK0hxQ2FaVkJ1Y2swClNTOWppNVVvMnpOUGg1eFB0ekwvdE1USWtkWDVDMEtrb2dWRU9yZktDdHMKLT4gQ0UtZ3JlYXNlICIgaTBVMGEwXwo1dDZ2MEVOUjk1RUhBeXZTZFhBZ3hweThoWVYyQXAyVi9QaVhjcXo2aHlSNDU3anI1T2RDY2RMV1A1Z2duaXl4CjY4cGR1aFBxMnk3Z1JoaTU3c1VhZ2dBUER5SkdGZnBBWmFrTWRlTFZvZjd5eVhFeAotLS0gQWVNb0pSR2M4cVhnUGtNMEhLS0NxcVNnM3VFUXdjckduL3ZNcGpoVFIvOAqpAEGKWr4tXsWSerdHxUfBd4nCTZDqlCU3FggkXPXXTfstPYCuU4VHCw==" }
CLOUDFLARE_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb0UyZkJmdy9Mcnl6NXRVZzZ1NEl4cnJNanZaSHNkalBoMWxzdzJCaUJNClZhQ2taT1dNWEtQMHFTRWRpRW9TKzVlK1VwTUJuM3lMZUIrZmZTTXVrcXcKLT4gb342UixtMiMtZ3JlYXNlIEp9UHkgX04gckVRYmAvCmxvbjlURDNXUlFVSnRpSlFCVmJrc3BwcEc0WmZQUFNXLzR5alpqUjlscjd3QnAzSXFLYlk2RmFHVkFQOW5zcVQKR3FHeEhUeSsreHMzCi0tLSBWMURua2Fac1hUVUp0aVdmQ3F2NjdWNUV6Q2ROL3d3bHY0UXF1MmFYK05rCqrYRugWh0HpiRNCWHeUNOu4vDEM02Euw3DF2Ud4L2HsO1wgZgrmD0HVRpr4Odr7jfsA7wmYALXNTCAqLTx2qVbiyg23rONSEA==" }
