CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:C1CBPDMX+rWtc6kNDdMtoLhQE63A/spsscc+Z4GfrDqKhcCR3ca+vw==,iv:RTW6PIrpjT17Q7YDFJ0/nLUEVm5kIXIqCUMHDB9HAb0=,tag:sgRYUMNZGuaAfFZG2wsuWA==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:NRmJ402E1lcxmwAWhU3igsGiah8=,iv:Ugo5U7S4lCmIJVXyTxFHj+PfLuHHmu+AY9+8cnOjiCM=,tag:sADH77TsE87xkiCuy2nzjw==,type:str]
KESTRA_DB_PASSWORD: ENC[AES256_GCM,data:UhBfKNmZwttb5gfhe6qY5JjzFmo=,iv:xrbYXELvbiWLes+ciMBcMJyOq+BfuZcGmP5VhwkiUMk=,tag:72z8FaTCdti5KYGmIil1GA==,type:str]
sops:
    age:
        - recipient: age1a27nce4x2lgvv655sgrmjeq4pnunarnqpy48rrwt2y9c2hc7458skhmqw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RCt6eTNPUXYremVNclJI
            eDR5MTU2c0NpR3UxMjYrSFdkMmJJcC9RL0V3ClhuZGZSTTR3c1pBai82Mjh5dlEw
            VGczWEYwN25SMUE2TUVjd2RtUTUwemcKLS0tIEZmaEwyVzBNc3FIeXJtSUxEYVpi
            S09HNEk5YzMvU24xTVFhcUYzaDdTNEUK3XFFDO+5g7VpHRcBxzM6nV2vz8AK7xd8
            R9jnC61uDnn3iZaMeLZNeByDK2D4kLrtmytyPsnwrAm9ibtXy4+Wgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T23:42:03Z"
    mac: ENC[AES256_GCM,data:kC4V0EUunOZcr0ylxOeFGAP12N+iW04HjrNvq+XZCMsGVncebSVJW7fiHEgv8b3Idef9Bn5hs3+OZIVQsJ4pvZjlCWwztlnsMmHhNv67LrZiabnYbihA51S/ol7VtBpWe99nin79xAF2iueUrf+yRRyFzeO4SbmuzAMjo65uw+Y=,iv:fYn9DF8IuC51NOkkaZ6n1xr0uoSJ4UQRQVvHwz6VGu8=,tag:uNLKxJJcD6CeRsWwga5J8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
