CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:C1CBPDMX+rWtc6kNDdMtoLhQE63A/spsscc+Z4GfrDqKhcCR3ca+vw==,iv:RTW6PIrpjT17Q7YDFJ0/nLUEVm5kIXIqCUMHDB9HAb0=,tag:sgRYUMNZGuaAfFZG2wsuWA==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:NRmJ402E1lcxmwAWhU3igsGiah8=,iv:Ugo5U7S4lCmIJVXyTxFHj+PfLuHHmu+AY9+8cnOjiCM=,tag:sADH77TsE87xkiCuy2nzjw==,type:str]
KESTRA_DB_PASSWORD: ENC[AES256_GCM,data:UhBfKNmZwttb5gfhe6qY5JjzFmo=,iv:xrbYXELvbiWLes+ciMBcMJyOq+BfuZcGmP5VhwkiUMk=,tag:72z8FaTCdti5KYGmIil1GA==,type:str]
READECK_DB_PASSWORD: ENC[AES256_GCM,data:Wt845bAD+nZ61JQnjx76p8rK6Yw=,iv:3F58se2iyetPMNOmWM0BPRG+Eqjxu7BLG3Rtkps1YPo=,tag:1DYM2rSIkhz7WTIzpOXvXQ==,type:str]
sops:
    age:
        - recipient: age1a27nce4x2lgvv655sgrmjeq4pnunarnqpy48rrwt2y9c2hc7458skhmqw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RCt6eTNPUXYremVNclJI
            eDR5MTU2c0NpR3UxMjYrSFdkMmJJcC9RL0V3ClhuZGZSTTR3c1pBai82Mjh5dlEw
            VGczWEYwN25SMUE2TUVjd2RtUTUwemcKLS0tIEZmaEwyVzBNc3FIeXJtSUxEYVpi
            S09HNEk5YzMvU24xTVFhcUYzaDdTNEUK3XFFDO+5g7VpHRcBxzM6nV2vz8AK7xd8
            R9jnC61uDnn3iZaMeLZNeByDK2D4kLrtmytyPsnwrAm9ibtXy4+Wgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T16:05:56Z"
    mac: ENC[AES256_GCM,data:3wT92Q2pGNpE6FYLTTk1U4UJeYt/EOfyA/LTGNmLY5orWJ+vV6NzjQVJNijAqeiz71sdf0gAvXgo1FU2FWZ0pD7VJ9z3vzoKz2v9KGHrLVD2dg9IkITVxDeCjQQDpz/JYVmFFPw6rYxYv0PahoA7WzRQ+WTuCHR1YQO9Q6RTSWY=,iv:4KXHoue+QJuKS0q/isZebWkcW/don1vBM0q/Z7Hfu7U=,tag:GtnteDVHyf6dFRInvzGTqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
