cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
kestra_db_password: "{{ lookup('env', 'KESTRA_DB_PASSWORD') }}"
readeck_db_password: "{{ lookup('env', 'READECK_DB_PASSWORD') }}"
librechat_db_password: "{{ lookup('env', 'LIBRECHAT_DB_PASSWORD') }}"
