cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"

# SMTP
smtp_mailer_from_address: "{{ lookup('env', 'SMTP_MAILER_FROM_ADDRESS') }}"

## Database role

# Postgres
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
kestra_db_password: "{{ lookup('env', 'KESTRA_DB_PASSWORD') }}"
readeck_db_password: "{{ lookup('env', 'READECK_DB_PASSWORD') }}"
librechat_db_password: "{{ lookup('env', 'LIBRECHAT_DB_PASSWORD') }}"

# MongoDB
mongo_initdb_root_password: "{{ lookup('env', 'MONGO_INITDB_ROOT_PASSWORD') }}"
librechat_mongodb_password: "{{ lookup('env', 'LIBRECHAT_MONGODB_PASSWORD') }}"

# Meilisearch
meili_master_key: "{{ lookup('env', 'MEILI_MASTER_KEY') }}"

# Librechat
librechat_creds_key: "{{ lookup('env', 'LIBRECHAT_CREDS_KEY') }}"
librechat_creds_iv: "{{ lookup('env', 'LIBRECHAT_CREDS_IV') }}"
librechat_jwt_secret: "{{ lookup('env', 'LIBRECHAT_JWT_SECRET') }}"
librechat_jwt_refresh_secret: "{{ lookup('env', 'LIBRECHAT_JWT_REFRESH_SECRET') }}"
librechat_smtp_username: "{{ lookup('env', 'LIBRECHAT_SMTP_USERNAME') }}"
librechat_smtp_password: "{{ lookup('env', 'LIBRECHAT_SMTP_PASSWORD') }}"
