cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"

## Database role

# Postgres
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
kestra_db_password: "{{ lookup('env', 'KESTRA_DB_PASSWORD') }}"
readeck_db_password: "{{ lookup('env', 'READECK_DB_PASSWORD') }}"
librechat_db_password: "{{ lookup('env', 'LIBRECHAT_DB_PASSWORD') }}"

# MongoDB
mongo_initdb_root_password: "{{ lookup('env', 'MONGO_INITDB_ROOT_PASSWORD') }}"
librechat_mongodb_password: "{{ lookup('env', 'LIBRECHAT_MONGODB_PASSWORD') }}"

# Meilisearch
meili_master_key: "{{ lookup('env', 'MEILI_MASTER_KEY') }}"
