---
cloudflare_zone: "{{ lookup('env', 'CLOUDFLARE_ZONE') }}"
cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"
letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"

spf_value: "v=spf1 ip4:{{ ansible_host }} -all"
dmarc_value: "v=DMARC1; p=none; rua=mailto:dmarc@{{ cloudflare_zone }}; adkim=s; aspf=s"
